//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMaster", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABB Boot Software.
        /// </summary>
        internal static string ABB_boot_software {
            get {
                return ResourceManager.GetString("ABB_boot_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABB Inverter.
        /// </summary>
        internal static string ABB_inverter {
            get {
                return ResourceManager.GetString("ABB_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Heat ABB.
        /// </summary>
        internal static string ABB_relay_heat {
            get {
                return ResourceManager.GetString("ABB_relay_heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAE company.
        /// </summary>
        internal static string about_us_txt {
            get {
                return ResourceManager.GetString("about_us_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitor.
        /// </summary>
        internal static string capacitor {
            get {
                return ResourceManager.GetString("capacitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers .
        /// </summary>
        internal static string careers {
            get {
                return ResourceManager.GetString("careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast sensor.
        /// </summary>
        internal static string Contrast_sensor {
            get {
                return ResourceManager.GetString("Contrast_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 customer care available.
        /// </summary>
        internal static string customer_care {
            get {
                return ResourceManager.GetString("customer_care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        internal static string customer_service {
            get {
                return ResourceManager.GetString("customer_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY GIFTS.
        /// </summary>
        internal static string daily_gifts {
            get {
                return ResourceManager.GetString("daily_gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Information.
        /// </summary>
        internal static string delivery_infomation {
            get {
                return ResourceManager.GetString("delivery_infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrtiption .
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Electric System - Automation.
        /// </summary>
        internal static string designElectric {
            get {
                return ResourceManager.GetString("designElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance sensor.
        /// </summary>
        internal static string Distance_sensor {
            get {
                return ResourceManager.GetString("Distance_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyeing Industry.
        /// </summary>
        internal static string dyeing {
            get {
                return ResourceManager.GetString("dyeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Automation.
        /// </summary>
        internal static string electronicAutomation {
            get {
                return ResourceManager.GetString("electronicAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express delivery withing 3 days.
        /// </summary>
        internal static string express_delivery {
            get {
                return ResourceManager.GetString("express_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY EXPRESS.
        /// </summary>
        internal static string express_delivery_title {
            get {
                return ResourceManager.GetString("express_delivery_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garment Industry.
        /// </summary>
        internal static string garment {
            get {
                return ResourceManager.GetString("garment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promotion for lucky customers.
        /// </summary>
        internal static string gifts {
            get {
                return ResourceManager.GetString("gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMI Mitsubishi.
        /// </summary>
        internal static string HMI_Mitsubishi {
            get {
                return ResourceManager.GetString("HMI_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inductive sensor.
        /// </summary>
        internal static string Inductive_sensor {
            get {
                return ResourceManager.GetString("Inductive_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Electronics.
        /// </summary>
        internal static string industrialElectronics {
            get {
                return ResourceManager.GetString("industrialElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string infomation {
            get {
                return ResourceManager.GetString("infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared sensor.
        /// </summary>
        internal static string Infrared_sensor {
            get {
                return ResourceManager.GetString("Infrared_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        internal static string instock {
            get {
                return ResourceManager.GetString("instock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Tweets.
        /// </summary>
        internal static string latestTweet {
            get {
                return ResourceManager.GetString("latestTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance -Setting Services - Textile - Dyeing Machines.
        /// </summary>
        internal static string mantainServices {
            get {
                return ResourceManager.GetString("mantainServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deasuring Device.
        /// </summary>
        internal static string measuringDevice {
            get {
                return ResourceManager.GetString("measuringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsbishi Inverter.
        /// </summary>
        internal static string mitsbishi_inverter {
            get {
                return ResourceManager.GetString("mitsbishi_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string mitsubishi {
            get {
                return ResourceManager.GetString("mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string mitsubishi1 {
            get {
                return ResourceManager.GetString("mitsubishi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misubishi cut off.
        /// </summary>
        internal static string mitsubishi_cutoff {
            get {
                return ResourceManager.GetString("mitsubishi_cutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular products.
        /// </summary>
        internal static string mostPopularProduct {
            get {
                return ResourceManager.GetString("mostPopularProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Controller Mitsubishi.
        /// </summary>
        internal static string Motion_Controller_Mitsubishi {
            get {
                return ResourceManager.GetString("Motion_Controller_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Whishlist.
        /// </summary>
        internal static string myWhishlist {
            get {
                return ResourceManager.GetString("myWhishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        internal static string newArrival {
            get {
                return ResourceManager.GetString("newArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Spare Part Textile - Dyeing Machines.
        /// </summary>
        internal static string newArrivals {
            get {
                return ResourceManager.GetString("newArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Counter.
        /// </summary>
        internal static string Omron_counter {
            get {
                return ResourceManager.GetString("Omron_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Inverter.
        /// </summary>
        internal static string Omron_inverter {
            get {
                return ResourceManager.GetString("Omron_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Level Sensor.
        /// </summary>
        internal static string Omron_level_sensor {
            get {
                return ResourceManager.GetString("Omron_level_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Light Sensor.
        /// </summary>
        internal static string Omron_light_sensor {
            get {
                return ResourceManager.GetString("Omron_light_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Proximity Sensor.
        /// </summary>
        internal static string Omron_proximity_sensor {
            get {
                return ResourceManager.GetString("Omron_proximity_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Pulse Source.
        /// </summary>
        internal static string Omron_pulse_source {
            get {
                return ResourceManager.GetString("Omron_pulse_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Temperature Controller.
        /// </summary>
        internal static string Omron_Temperature_Controller {
            get {
                return ResourceManager.GetString("Omron_Temperature_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Travel Switch.
        /// </summary>
        internal static string Omron_travel_switch {
            get {
                return ResourceManager.GetString("Omron_travel_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Ultrasound Sensor.
        /// </summary>
        internal static string Omron_Ultrasound_Sensor {
            get {
                return ResourceManager.GetString("Omron_Ultrasound_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical sensors.
        /// </summary>
        internal static string Optical_sensors {
            get {
                return ResourceManager.GetString("Optical_sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT CONTACTS.
        /// </summary>
        internal static string our_contacts {
            get {
                return ResourceManager.GetString("our_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi.
        /// </summary>
        internal static string PLC_Mitsubishi {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi Micro.
        /// </summary>
        internal static string PLC_Mitsubishi_Micro {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi_Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi Modular.
        /// </summary>
        internal static string PLC_Mitsubishi_Modular {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi_Modular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure sensors.
        /// </summary>
        internal static string Pressure_sensors {
            get {
                return ResourceManager.GetString("Pressure_sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Tools.
        /// </summary>
        internal static string programmingTools {
            get {
                return ResourceManager.GetString("programmingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity sensor.
        /// </summary>
        internal static string Proximity_sensor {
            get {
                return ResourceManager.GetString("Proximity_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistor.
        /// </summary>
        internal static string resistor {
            get {
                return ResourceManager.GetString("resistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCHING.
        /// </summary>
        internal static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result with .
        /// </summary>
        internal static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string sensor {
            get {
                return ResourceManager.GetString("sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo Mitsubishi.
        /// </summary>
        internal static string Servo_Mitsubishi {
            get {
                return ResourceManager.GetString("Servo_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup .
        /// </summary>
        internal static string setupSystem {
            get {
                return ResourceManager.GetString("setupSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemnens Boot Software.
        /// </summary>
        internal static string Siemens_boot_software {
            get {
                return ResourceManager.GetString("Siemens_boot_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemens Inverter.
        /// </summary>
        internal static string Siemens_inverter {
            get {
                return ResourceManager.GetString("Siemens_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switchgear.
        /// </summary>
        internal static string switchgear {
            get {
                return ResourceManager.GetString("switchgear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Services .
        /// </summary>
        internal static string technicalServices {
            get {
                return ResourceManager.GetString("technicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature sensor.
        /// </summary>
        internal static string Temperature_sensor {
            get {
                return ResourceManager.GetString("Temperature_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textile Industry.
        /// </summary>
        internal static string textile {
            get {
                return ResourceManager.GetString("textile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textile Equipment.
        /// </summary>
        internal static string textileEquipment {
            get {
                return ResourceManager.GetString("textileEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Systems - Automation Solutions.
        /// </summary>
        internal static string threeItems {
            get {
                return ResourceManager.GetString("threeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an solution for automation electrical.
        /// </summary>
        internal static string titleSlide1a {
            get {
                return ResourceManager.GetString("titleSlide1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance and setting textile machine..
        /// </summary>
        internal static string titleSlide1b {
            get {
                return ResourceManager.GetString("titleSlide1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance -Setting Services - Textile - Dyeing Machines.
        /// </summary>
        internal static string twoItems {
            get {
                return ResourceManager.GetString("twoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultrasonic sensors.
        /// </summary>
        internal static string Ultrasonic_sensors {
            get {
                return ResourceManager.GetString("Ultrasonic_sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
