//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMaster", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABB Boot Software.
        /// </summary>
        internal static string ABB_boot_software {
            get {
                return ResourceManager.GetString("ABB_boot_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABB Inverter.
        /// </summary>
        internal static string ABB_inverter {
            get {
                return ResourceManager.GetString("ABB_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Heat ABB.
        /// </summary>
        internal static string ABB_relay_heat {
            get {
                return ResourceManager.GetString("ABB_relay_heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitor.
        /// </summary>
        internal static string capacitor {
            get {
                return ResourceManager.GetString("capacitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrtiption .
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Electric System - Automation.
        /// </summary>
        internal static string designElectric {
            get {
                return ResourceManager.GetString("designElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Automation.
        /// </summary>
        internal static string electronicAutomation {
            get {
                return ResourceManager.GetString("electronicAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMI Mitsubishi.
        /// </summary>
        internal static string HMI_Mitsubishi {
            get {
                return ResourceManager.GetString("HMI_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Electronics.
        /// </summary>
        internal static string industrialElectronics {
            get {
                return ResourceManager.GetString("industrialElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string infomation {
            get {
                return ResourceManager.GetString("infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain System.
        /// </summary>
        internal static string mantainServices {
            get {
                return ResourceManager.GetString("mantainServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deasuring Device.
        /// </summary>
        internal static string measuringDevice {
            get {
                return ResourceManager.GetString("measuringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsbishi Inverter.
        /// </summary>
        internal static string mitsbishi_inverter {
            get {
                return ResourceManager.GetString("mitsbishi_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string mitsubishi {
            get {
                return ResourceManager.GetString("mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string mitsubishi1 {
            get {
                return ResourceManager.GetString("mitsubishi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misubishi cut off.
        /// </summary>
        internal static string mitsubishi_cutoff {
            get {
                return ResourceManager.GetString("mitsubishi_cutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular products.
        /// </summary>
        internal static string mostPopularProduct {
            get {
                return ResourceManager.GetString("mostPopularProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Controller Mitsubishi.
        /// </summary>
        internal static string Motion_Controller_Mitsubishi {
            get {
                return ResourceManager.GetString("Motion_Controller_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Whishlist.
        /// </summary>
        internal static string myWhishlist {
            get {
                return ResourceManager.GetString("myWhishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        internal static string newArrival {
            get {
                return ResourceManager.GetString("newArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        internal static string newArrivals {
            get {
                return ResourceManager.GetString("newArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Counter.
        /// </summary>
        internal static string Omron_counter {
            get {
                return ResourceManager.GetString("Omron_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Inverter.
        /// </summary>
        internal static string Omron_inverter {
            get {
                return ResourceManager.GetString("Omron_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Level Sensor.
        /// </summary>
        internal static string Omron_level_sensor {
            get {
                return ResourceManager.GetString("Omron_level_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Light Sensor.
        /// </summary>
        internal static string Omron_light_sensor {
            get {
                return ResourceManager.GetString("Omron_light_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Proximity Sensor.
        /// </summary>
        internal static string Omron_proximity_sensor {
            get {
                return ResourceManager.GetString("Omron_proximity_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Pulse Source.
        /// </summary>
        internal static string Omron_pulse_source {
            get {
                return ResourceManager.GetString("Omron_pulse_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Temperature Controller.
        /// </summary>
        internal static string Omron_Temperature_Controller {
            get {
                return ResourceManager.GetString("Omron_Temperature_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Travel Switch.
        /// </summary>
        internal static string Omron_travel_switch {
            get {
                return ResourceManager.GetString("Omron_travel_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omron Ultrasound Sensor.
        /// </summary>
        internal static string Omron_Ultrasound_Sensor {
            get {
                return ResourceManager.GetString("Omron_Ultrasound_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi.
        /// </summary>
        internal static string PLC_Mitsubishi {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi Micro.
        /// </summary>
        internal static string PLC_Mitsubishi_Micro {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi_Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mitsubishi Modular.
        /// </summary>
        internal static string PLC_Mitsubishi_Modular {
            get {
                return ResourceManager.GetString("PLC_Mitsubishi_Modular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Tools.
        /// </summary>
        internal static string programmingTools {
            get {
                return ResourceManager.GetString("programmingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string sensor {
            get {
                return ResourceManager.GetString("sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo Mitsubishi.
        /// </summary>
        internal static string Servo_Mitsubishi {
            get {
                return ResourceManager.GetString("Servo_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup .
        /// </summary>
        internal static string setupSystem {
            get {
                return ResourceManager.GetString("setupSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemnens Boot Software.
        /// </summary>
        internal static string Siemens_boot_software {
            get {
                return ResourceManager.GetString("Siemens_boot_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemens Inverter.
        /// </summary>
        internal static string Siemens_inverter {
            get {
                return ResourceManager.GetString("Siemens_inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switchgear.
        /// </summary>
        internal static string switchgear {
            get {
                return ResourceManager.GetString("switchgear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Services .
        /// </summary>
        internal static string technicalServices {
            get {
                return ResourceManager.GetString("technicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textile Equipment.
        /// </summary>
        internal static string textileEquipment {
            get {
                return ResourceManager.GetString("textileEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Items.
        /// </summary>
        internal static string threeItems {
            get {
                return ResourceManager.GetString("threeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Items.
        /// </summary>
        internal static string twoItems {
            get {
                return ResourceManager.GetString("twoItems", resourceCulture);
            }
        }
    }
}
